### ISSUE TITLE
I've to recreate my timer each time I open the app

### ISSUE THREAD

**Issue by Selemia** [guglielmilo/notificationtimer#1]
Hi Guillaume,

I have used your app on my mobile (Xiaomi Redmi Note 11 Pro 5G) for the past several years, thanks for that.
I'm using only one timer and lately, I've to recreate it each time I open the app.
It seems my timer is not saved anymore when I close the app.

Thanks by advance for your answer.

**Comment by guillaumemilitello** [comment]
Hi Selemia,
Thank you for using the app and reporting this issue.
Can you please elaborate or send me more details in order to reproduce the issue? Repro steps, images or videos would help me.
Also what is your Android version? Did you recently update your Android version?
Thanks,
Guillaume

**Comment by Selemia** [comment]
Thank you for considering my issue ;)

Here is my "about phone":
![Screenshot_2024-12-12-22-44-58-177_com android settings](https://github.com/user-attachments/assets/4e312500-5718-4913-aeb7-489a3d7434ac)

I didn't upgrade my android major version recently (I only had several security updates)

Steps to reproduce my issue are pretty simple:

First, I create a new timer:
![Screenshot_2024-12-12-22-36-25-274_com notification timer](https://github.com/user-attachments/assets/a7477302-f603-4da5-8df4-c1cac736fe8f)

Then, I rename the timer (or not, in fact, it makes no difference):
![Screenshot_2024-12-12-22-36-49-877_com notification timer](https://github.com/user-attachments/assets/4c5e8fd3-038a-4ada-a93e-627da1bf1dea)

I start the timer (or not, in fact, it makes no difference):
![Screenshot_2024-12-12-22-36-59-265_com notification timer](https://github.com/user-attachments/assets/57fe791b-be3d-40f1-a3b2-fe3914cb1d11)

I close the app, stop the timer and the notification:
![Screenshot_2024-12-12-22-37-06-080_com miui home](https://github.com/user-attachments/assets/07ceaa2a-2304-435a-b56b-c0b17221cc2a)
![Screenshot_2024-12-12-22-37-16-264_com miui home](https://github.com/user-attachments/assets/a9437ac1-d8a1-493d-a1d0-edbbfdaa8f5e)

I restart the application and the timers list remains empty:
![Screenshot_2024-12-12-22-37-25-752_com notification timer](https://github.com/user-attachments/assets/e01b1705-d699-40c8-a7d0-6fd6b6b15d3a)

**Comment by guillaumemilitello** [comment]
If I recall correctly it is by design if you don't save it.
You can save it with the plus sign. You can then have multiple timers in the list and drag and drop them in the order you want.
![copy_8805874596034923418](https://github.com/user-attachments/assets/55c6bdd5-776a-4ea7-bfe8-97afdc76f099)
Let me know of it helps.

**Comment by Selemia** [comment]
You're right, it works.
I don't know why my previous timer was deleted, I created it several years ago.
And I forgot how to save the new one.
Thanks Guillaume
